### ISSUE TITLE
function Copy in file client.go did not catch any exception

### ISSUE THREAD

**Issue by ymyuan** [bramvdbogaerde/go-scp#7] opened 2018-06-11 08:40 UTC
When i use this
I found it always seems like execuate successfully, but it is NOT
So when I debug the function CopyFile, i found  function Copy report err

How about change to following code:
err := a.Session.Run("/usr/bin/scp -qrt " + directory)
if err != nil{
     **********
}

**Comment by bramvdbogaerde** [comment] 2018-06-11 18:51
I will check it out. 
Thanks for reporting.

**Comment by bramvdbogaerde** [comment] 2018-06-11 19:48
It seems that the scp command always returns status code 1 (indicating an error, since it is a non-zero exit code) regardless of the actual success or failure of the transfer, with the current code.

Maybe this is because the way we are ending the transfer but I'm not sure.
I will look into this futher, if you have an idea or a proposal in order to resolve this issue, please tell so.

Thanks for reporting.

**Comment by bramvdbogaerde** [comment] 2018-06-13 13:17
You mean ssh to the server and checking if the file is there and has the correct size, permissions, ...

I personally think that it would further (maybe unnecessary) complicate the code.

The thing is that it seems quite strange to me that scp returns a non-zero exit code even when everything succeeded as instructed. This can be caused by incorrect termination of the scp procces or by an unstandard way of exiting the proccess by the scp program. If it is the former then we should fix it in our code, if the latter than we must find another way to check if scp has succeeded, maybe by using the output of stderror.

But first I would like to check if we correctly terminate scp before we start creating workarounds.

**Comment by hustneverland** [comment] 2018-11-18 12:30
i have meet the same problem. maybe because scp copy stdin is not a standard method?

**Comment by bramvdbogaerde** [comment] 2018-11-18 15:29
The SCP protocol works along these lines:

* Initialize a SSH connection with the server the data must be copied to
* Execute SCP on the remote server in target (sink) mode, this is achieved using the "scp -t" command.
* Open data pipes (ie. connect to the STDIN, STDOUT and STDERROR from the SSH connection)
* Exchange a few control messages, like the name of the file, permissions and length
* Exchange the file itself
* End the process, close all inputs and outputs and close the SSH connection

This is how it is implemented in famous SSH libraries like libssh [1] and how it is documented everywhere else. So it definitely is the "standard method" for copying files.

The error you got in issue #11 is probably because you forgot to pass the "-t" parameter as well resulting in an invalid scp command (hence the usage error you got in your /tmp/out).

The thing the library isn't handling right now is status messages that migh be send back through the STDOUT of the "scp -t" process. 

\[1\]   [ibssh scp implementation](https://github.com/rofl0r/libssh/blob/05e295fcb5766bf57fdf9b377d0de853d64bae09/src/scp.c)

**Comment by acls** [comment] 2018-12-13 22:40
`fmt.Fprintln(w, "\x00")` should be
`fmt.Fprint(w, "\x00")`

**Comment by bramvdbogaerde** [comment] 2018-12-14 08:51
That error was fixed in pull request #9

**Comment by bramvdbogaerde** [comment] 2019-08-31 15:06
This should be fully fixed in 50cfc22f160ef330453db02ad70b5c90fb718c56.

**Closed by bramvdbogaerde** 2019-08-31 15:06 UTC
