### ISSUE TITLE
Fail when copy big files

### ISSUE THREAD

**Issue by segator** [bramvdbogaerde/go-scp#26] opened 2020-02-10 20:35 UTC
It crash on this line 
_, err = fmt.Fprintln(w, "C"+permissions, size, filename) line 129 client.go
when size is big(+2gb) or name with special chars.

For example 
```
my FiLE [AMZ][DUAL-DDR].mkv
```
response --> scp: ambiguous target

**Comment by bramvdbogaerde** [comment] 2020-02-10 22:20
Thanks for filing the bug report.

I will try to reproduce it myself and will get back to you as soon as 
possible.

Regards,

Bram

**Comment by ramondeklein** [comment] 2021-02-14 16:43
It seems the implementation is a bit weird, when you use `CopyFile` with a large file, because it will read everything in memory. When using `CopyFromFile` it will call `Stat` on the file-descriptor which is much more efficient of course.

**Comment by bramvdbogaerde** [comment] 2021-02-14 17:06
The naming of these functions might be a little bit confusing indeed, but this is mostly due to backwards compatibility reasons.

As it stands at the moment, you have a few options for copying some data:

* `CopyFile`: the original implementation, can be used when the file size is not known beforehand, but needs to be computed. The issue here is that it accepts an io.Reader which doesn't provide any information about how many bytes are left at all, this means that program must read from the reader until it is exhausted, and then compute the size based on that. The file needs to be kept in memory, because the size must be sent before the file contents themselves (according to the SCP protocol).
* `CopyFromFile`: although a little bit confusing, this is the function that you need to use when copying from the file system. Because an `os.File` is passed, `Stat` can indeed provide the size of the file we are about to copy
* `Copy` and `CopyPassThru` can be used in situations where you have an `io.Reader`, and the final size of the file, this is more low-level and can be used when you want more control over the copying process.

`CopyFile` might indeed have some memory issues, but if you are not copying from the file system, you either need to use that, `Copy` or `CopyPassThru`. The former computes the the final file size for you, but at a price, while the latter requires you to compute the final size yourself.

I hope that clears some of the confusion, I am always open for suggestion on how to improve its design and performance.

**Comment by bramvdbogaerde** [comment] 2021-05-27 19:44
The ambiguous target error should have been fixed in pull request #41.

Please re-open if this doesn't fix your issue.

**Closed by bramvdbogaerde** 2021-05-27 19:44 UTC
